### ISSUE TITLE
Period Classes

### ISSUE THREAD

**Issue by annoyingmouse** [sbstjn/timesheet.js#16]
Cracking work - having loads of fun with it. Had an issue with classes not being parsed correctly for periods with only one time so altered line 88 to read:

    var cat = data[n].length === 4 ? data[n][3] : data[n].length === 3 ? data[n][2] : 'default';

Hope that it helps.

**Comment by sbstjn** [comment]
Would you mind creating a PR? :+1:

**Comment by annoyingmouse** [comment]
Will do so tomorrow if that's okay? Too tired now ;-)

**Comment by annoyingmouse** [comment]
There you go, my first Pull Request - hope it's okay?

**Comment by sbstjn** [comment]
Thanks.
