### ISSUE TITLE
Available via cdnjs 

### ISSUE THREAD

**Issue by paazmaya** [sbstjn/timesheet.js#36]
Please make it available via https://github.com/cdnjs/cdnjs

**Comment by kdabir** [comment]
In the meantime [rawgit](https://rawgit.com) can be used. For example, https://cdn.rawgit.com/sbstjn/timesheet.js/master/dist/timesheet.js and https://cdn.rawgit.com/sbstjn/timesheet.js/master/dist/timesheet.css can be used to link directly to the assets served with correct headers (not `text/plain`).

**Comment by kdabir** [comment]
By the Way, the URLs above need to be updated to
https://cdn.rawgit.com/sbstjn/timesheet.js/master/dist/timesheet.min.js
and https://cdn.rawgit.com/sbstjn/timesheet.js/master/dist/timesheet.min.css
